@startuml

title __MATH's Class Diagram__\n


        class com.example.calc.math.Calculator {
            - a : SimpleDoubleProperty
            - b : SimpleDoubleProperty
            - c : SimpleDoubleProperty
            - chuvs : SimpleDoubleProperty
            - d : SimpleDoubleProperty
            - minus : SimpleDoubleProperty
            - pcminus : SimpleDoubleProperty
            - pcplus : SimpleDoubleProperty
            - plus : SimpleDoubleProperty
            - rasp : SimpleDoubleProperty
            - spec : SimpleDoubleProperty
            + Calculator()
            + aProperty()
            + bProperty()
            + cProperty()
            + calcChuvs()
            + calcMinusBol()
            + calcPCMinus()
            + calcPCPlus()
            + calcPlusBol()
            + calcRasp()
            + calcSpec()
            + chuvsProperty()
            + dProperty()
            + getA()
            + getB()
            + getC()
            + getChuvs()
            + getD()
            + getMinus()
            + getPcminus()
            + getPcplus()
            + getPlus()
            + getRasp()
            + getSpec()
            + minusProperty()
            + pcminusProperty()
            + pcplusProperty()
            + plusProperty()
            + raspProperty()
            + setA()
            + setB()
            + setC()
            + setChuvs()
            + setD()
            + setMinus()
            + setPcminus()
            + setPcplus()
            + setPlus()
            + setRasp()
            + setSpec()
            + specProperty()
        }

  


        interface com.example.calc.math.MathCalc {
            {abstract} + calcChuvs()
            {abstract} + calcMinusBol()
            {abstract} + calcPCMinus()
            {abstract} + calcPCPlus()
            {abstract} + calcPlusBol()
            {abstract} + calcRasp()
            {abstract} + calcSpec()
        }

  

  com.example.calc.math.Calculator .up.|> com.example.calc.math.MathCalc


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
